# Generated by Django 5.1.3 on 2024-12-08 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_default_user(apps, schema_editor):
    """
    Assign a default user to existing carts.
    """
    Cart = apps.get_model('myapp', 'Cart')
    User = apps.get_model('auth', 'User')

    # Create a default user if it does not exist
    default_user, created = User.objects.get_or_create(
        username='default_user',
        defaults={'email': 'default@example.com', 'password': 'defaultpassword'}
    )

    # Update all existing cart rows to assign the default user
    for cart in Cart.objects.all():
        cart.user = default_user
        cart.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_product_category_alter_product_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.CASCADE,
                null=True,  # Temporarily allow null
                related_name='cart_set_2'
            ),
        ),
        migrations.RunPython(assign_default_user),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cart_set_2'
            ),
        ),
    ]
